# Generated by Django 2.1.3 on 2018-11-17 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_title', models.CharField(max_length=255)),
                ('episode_number', models.IntegerField()),
                ('file_url', models.URLField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('episode_desc', models.TextField()),
            ],
        ),
    ]
