# Generated by Django 2.1.3 on 2018-11-17 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='img_url',
            field=models.URLField(default='http://dummyurl.com/'),
            preserve_default=False,
        ),
    ]
