# Generated by Django 2.1.3 on 2018-11-17 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0002_podcast_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Youtube',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('video_description', models.TextField()),
            ],
        ),
    ]
