# Generated by Django 2.1.3 on 2019-01-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0004_auto_20181215_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='episode_number',
            field=models.FloatField(),
        ),
    ]
