# Generated by Django 2.1.3 on 2019-01-12 02:02
import csv
from datetime import datetime
from django.db import migrations
from django.utils.timezone import make_aware


def insert_initial_data(apps, schema_editor):
    podcast = apps.get_model('bideosite', 'Podcast')
    with open('bideosite/migrations/bideosite_podcast001.csv') as f:
        reader = csv.reader(f)
        for row in reader:
            if row[0] != 'id':
                _, created = podcast.objects.get_or_create(
                    # id=row[0],
                    episode_title=row[1],
                    episode_number=row[2],
                    file_url=row[3],
                    pub_date=datetime.strptime(row[4], '%Y-%m-%d %H:%M:%S %z'),
                    episode_desc=row[5],
                    img_url=row[6]
                )


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0005_auto_20190112_1428'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data),
    ]
