# Generated by Django 2.1.3 on 2019-01-18 05:31

from django.db import migrations, models
from datetime import datetime


class Migration(migrations.Migration):

    default_time = datetime.strptime('2005-02-14 12:00:00 +0000', '%Y-%m-%d %H:%M:%S %z')

    dependencies = [
        ('bideosite', '0006_auto_20190111_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='pub_date',
            field=models.DateTimeField(default=default_time, verbose_name='date published'),
        ),
    ]
