# Generated by Django 2.1.3 on 2019-01-18 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0006_auto_20190111_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtube',
            name='pub_date',
            field=models.DateTimeField(default='2005-02-14 12:00:00', verbose_name='date published'),
        ),
    ]
