# Generated by Django 2.1.3 on 2019-07-14 22:02

from django.db import migrations


def insert_initial_data(apps, schema_editor):
    YoutubeChannel = apps.get_model('bideosite', 'YoutubeChannel')
    YoutubeChannel.objects.get_or_create(
        channel_name='Nornsy', channel_id='UCWXryWl_0ZJQyCZeKGJ-hMQ')
    YoutubeChannel.objects.get_or_create(
        channel_name='Blinkoom', channel_id='UC-1uElslFn4lVy5pVAYua3w')


class Migration(migrations.Migration):

    dependencies = [
        ('bideosite', '0008_create_youtubechannel'),
    ]

    operations = [
        migrations.RunPython(insert_initial_data)
    ]
